
import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */

public class aplikasipertambahanangka extends javax.swing.JFrame {

    /**
     * Creates new form aplikasipertambahanangka
     */
    public aplikasipertambahanangka() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Bil1TextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Bil2TextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        HasilTextField = new javax.swing.JTextField();
        tambahButton1 = new javax.swing.JButton();
        kurangjButton2 = new javax.swing.JButton();
        kalijButton3 = new javax.swing.JButton();
        bagijButton4 = new javax.swing.JButton();
        exitjButton5 = new javax.swing.JButton();
        clearjButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setText("bilangan 1");

        Bil1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bil1TextFieldActionPerformed(evt);
            }
        });
        Bil1TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Bil1TextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bil1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Bil1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jLabel2.setText("bilangan 2");

        Bil2TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Bil2TextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bil2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Bil2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 102, 255));

        jLabel3.setText("Hasil");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(37, 37, 37)
                .addComponent(HasilTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HasilTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tambahButton1.setText("Tambah");
        tambahButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButton1ActionPerformed(evt);
            }
        });

        kurangjButton2.setText("Kurang");
        kurangjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangjButton2ActionPerformed(evt);
            }
        });

        kalijButton3.setText("Kali");
        kalijButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kalijButton3ActionPerformed(evt);
            }
        });

        bagijButton4.setText("Bagi");
        bagijButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagijButton4ActionPerformed(evt);
            }
        });

        exitjButton5.setText("Exit");
        exitjButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitjButton5ActionPerformed(evt);
            }
        });

        clearjButton6.setText("clear");
        clearjButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearjButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearjButton6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tambahButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kurangjButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kalijButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bagijButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(exitjButton5)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahButton1)
                    .addComponent(kurangjButton2)
                    .addComponent(kalijButton3)
                    .addComponent(bagijButton4)
                    .addComponent(exitjButton5))
                .addGap(18, 18, 18)
                .addComponent(clearjButton6)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bil1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bil1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bil1TextFieldActionPerformed

    private void kurangjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangjButton2ActionPerformed
        // TODO add your handling code here:
        Double bil1 = Double.parseDouble(Bil1TextField.getText());
        Double bil2 = Double.parseDouble(Bil2TextField.getText());
        //proses penjumlahan
        Double hasil = bil1-bil2;
        //set textnya masuk kedalam textfield
        HasilTextField.setText(Double.toString(hasil));       
    }//GEN-LAST:event_kurangjButton2ActionPerformed

    private void kalijButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kalijButton3ActionPerformed
        // TODO add your handling code here:
        Double bil1 = Double.parseDouble(Bil1TextField.getText());
        Double bil2 = Double.parseDouble(Bil2TextField.getText());
        //proses penjumlahan
        Double hasil = bil1*bil2;
        //set textnya masuk kedalam textfield
        HasilTextField.setText(Double.toString(hasil));        
    }//GEN-LAST:event_kalijButton3ActionPerformed

    private void tambahButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButton1ActionPerformed
        // TODO add your handling code here:
        Double bil1 = Double.parseDouble(Bil1TextField.getText());
        Double bil2 = Double.parseDouble(Bil2TextField.getText());
        //proses penjumlahan
        Double hasil = bil1+bil2;
        //set textnya masuk kedalam textfield
        HasilTextField.setText(Double.toString(hasil));
    }//GEN-LAST:event_tambahButton1ActionPerformed

    private void bagijButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagijButton4ActionPerformed
        // TODO add your handling code here:
        Double bil1 = Double.parseDouble(Bil1TextField.getText());
        Double bil2 = Double.parseDouble(Bil2TextField.getText());
        //proses penjumlahan
        Double hasil = bil1/bil2;
        //set textnya masuk kedalam textfield
        HasilTextField.setText(Double.toString(hasil));
    }//GEN-LAST:event_bagijButton4ActionPerformed

    private void exitjButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitjButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitjButton5ActionPerformed

    private void clearjButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearjButton6ActionPerformed
        // TODO add your handling code here:
        Bil1TextField.setText("");
        Bil2TextField.setText("");
        HasilTextField.setText("");
    }//GEN-LAST:event_clearjButton6ActionPerformed
    private void filterTombol(java.awt.event.KeyEvent evt){
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)))
            {
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "masukkan hanya angka 0 s/d 9");
                evt.consume(); 
        
            }
    }
        
    private void Bil1TextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Bil1TextFieldKeyTyped
        //filterTombol(evt);
        filterTombol(evt);
//        char c = evt.getKeyChar();
//            if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)))
//            {
//                getToolkit().beep();
//                JOptionPane.showMessageDialog(null, "masukkan hanya angka 0 s/d 9");
//                evt.consume();
//            }
    }//GEN-LAST:event_Bil1TextFieldKeyTyped

    private void Bil2TextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Bil2TextFieldKeyTyped
        // filterTombol (evt);
        filterTombol(evt);
//        char c = evt.getKeyChar();
//            if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)))
//            {
//                getToolkit().beep();
//                JOptionPane.showMessageDialog(null, "masukkan hanya angka 0 s/d 9");
//                evt.consume();
//            }
    }//GEN-LAST:event_Bil2TextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aplikasipertambahanangka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aplikasipertambahanangka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aplikasipertambahanangka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aplikasipertambahanangka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aplikasipertambahanangka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bil1TextField;
    private javax.swing.JTextField Bil2TextField;
    private javax.swing.JTextField HasilTextField;
    private javax.swing.JButton bagijButton4;
    private javax.swing.JButton clearjButton6;
    private javax.swing.JButton exitjButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton kalijButton3;
    private javax.swing.JButton kurangjButton2;
    private javax.swing.JButton tambahButton1;
    // End of variables declaration//GEN-END:variables
}
